const base = 0xa4700000;

/// (Power-saving) mode options.  See
/// https://n64brew.dev/wiki/RDRAM_Interface#0x0470_0000_-_RI_MODE for
/// more details.
pub const Mode = packed struct(u32) {
    /// SMode packet controls; determines how often the RI sends SMode
    /// packets to RDRAM modules.  Usually set to `.allow_standby`.
    op_mode: enum(u2) {
        /// Continuously send packets (after every BusClk cycle);
        /// RDRAM modules reset after 272 BusClk cycles.
        reset,
        /// Send packets every 4th BusClk cycle; RDRAM modules always
        /// stay active / never enter standby mode.
        always_active,
        /// Send packets before each RDRAM transaction; RDRAM modules
        /// enter standby mode when transactions complete.
        allow_standby,
        /// Unknown (try it at your own risk!).
        unknown,
    } = .allow_standby,
    /// Should the RAC transmit logic clocks automatically halt
    /// when not in use?  (Normally yes.)
    stop_t: bool = true,
    /// Should the RAC receive logic clocks automatically halt when
    /// not in use?  (Normally yes.)
    stop_r: bool = true,
    /// Unused.
    unused: u28 = 0,
};
pub const mode: *volatile Mode = @ptrFromInt(base + 0x0);

/// (Current control) configuration options.  See
/// https://n64brew.dev/wiki/RDRAM_Interface#0x0470_0004_-_RI_CONFIG
/// for more details;
/// https://n64brew.dev/wiki/RDRAM#Current_Control_calibration
/// provides even more details on what these values mean.
pub const Config = packed struct(u32) {
    /// Value for the current control register when automatic current
    /// control (AutoCC) is disabled / RAC CCtlEn signal is low.
    cc: u5,
    /// Should the RAC use automatic current control (AutoCC)?
    auto_cc: bool,
    /// Unused.
    unused: u26,
};
pub const config: *volatile Config = @ptrFromInt(base + 0x4);

/// When written with any value, loads `RI.config.cc` into the RAC's
/// current control register if `RI.config.auto_cc` is false (or an
/// internal/autogenerated value if `RI.config.auto_cc` is true).
/// Reading is officially undefined, but on the N64 returns bits from
/// other RI registers.  See
/// https://n64brew.dev/wiki/RDRAM_Interface#0x0470_0008_-_RI_CURRENT_LOAD
/// for more details.
pub const CurrentLoad = packed struct(u32) {
    /// Value from `RI.error.ack`.
    error_ack: bool,
    /// Always 3 (0b11) as far as anyone knows.
    unused1: u2 = 3,
    /// Value from `RI.mode.stop_r`.
    mode_stop_r: bool,
    /// Value from `RI.select.tsel[0]`.
    select_tsel_0: bool,
    /// Always 0 as far as anyone knows.
    unused2: u27,
};
pub const current_load: *volatile CurrentLoad = @ptrFromInt(base + 0x8);

/// Signal timing options.  See
/// https://n64brew.dev/wiki/RDRAM_Interface#0x0470_000C_-_RI_SELECT
/// for more details.
pub const Select = packed struct(u32) {
    /// Timings for receive signals.  Only known-good value is
    /// `0b0100`.
    rsel: u4 = 4,
    /// Timings for transmit signals.  Only known good value is
    /// `0b0001`.
    tsel: u4 = 1,
    /// Unused.
    unused: u24,
};
pub const select: *volatile Select = @ptrFromInt(base + 0xc);

/// Refresh-related options.  See
/// https://n64brew.dev/wiki/RDRAM_Interface#0x0470_0010_-_RI_REFRESH
/// for more details.
pub const Refresh = packed struct(u32) {
    /// For previously-clean banks, how many cycles to wait after
    /// refresh.  Usually 52.
    clean_refresh_delay: u8 = 52,
    /// For previously-dirty banks, how many cycles to wait after
    /// refresh.  Usually 54.
    dirty_refresh_delay: u8 = 54,
    /// Oscillates during operation (is this the bank currently being
    /// refreshed?).
    bank: bool,
    /// Automatically refresh?  (Usually yes.)
    auto_refresh: bool = true,
    /// Optimize?  (Usually yes.)
    optimize: bool = true,
    /// Which RDRAM modules (0-3) are multi-bank?
    multi_bank: [4]bool,
    /// Unused.
    unused: u9,
};
pub const refresh: *volatile Refresh = @ptrFromInt(base + 0x10);

/// Latency-related settings.  See
/// https://n64brew.dev/wiki/RDRAM_Interface#0x0470_0014_-_RI_LATENCY
/// for more details.
pub const Latency = packed struct(u32) {
    /// Possibly controls the maximum DMA transfer size.  Usually `0xf`.
    dma_latency_overlap: u4 = 0xf,
    /// Unused.
    unused: u28,
};
pub const latency: *volatile Latency = @ptrFromInt(base + 0x14);

/// Reported RDRAM errors.  Writing any value to this register clears
/// the reported errors.  See
/// https://n64brew.dev/wiki/RDRAM_Interface#0x0470_0018_-_RI_ERROR
/// for more details.
pub const Errors = packed struct(u32) {
    /// Did the RI expect an Ack but never received it?
    ack: bool,
    /// Did the RI receive a NAck it didn't expect?
    nack: bool,
    /// Was there an attempt to write to an out-of-range address
    /// (`0x00800000` - `0x03efffff`)?
    over: bool,
    /// Unused.
    unused: u29,
};
pub const errors: *volatile Errors = @ptrFromInt(base + 0x18);

/// Bank statuses.  Writing any value to this register will invalidate
/// all banks, i.e. marking all banks as invalid and dirty.  See
/// https://n64brew.dev/wiki/RDRAM_Interface#0x0470_001c_-_RI_BANK_STATUS
/// for more details.
pub const BankStatus = packed struct(u32) {
    /// Which banks (0-7) are valid?
    valid: [8]bool,
    /// Which banks (0-7) are dirty?
    dirty: [8]bool,
    /// Unused.
    unused: u16,
};
pub const bank_status: *volatile BankStatus = @ptrFromInt(base + 0x1c);
